# Changes here will be overwritten by Copier
_commit: v0.1.22
_src_path: https://github.com/fohte/generic-boilerplate
description: Personal CLI toolkit written in Rust
is_public: true
release_type: rust
type: base
use_release_please: true
