# Changes here will be overwritten by Copier
_commit: v0.1.25
_src_path: https://github.com/fohte/generic-boilerplate
description: Personal CLI toolkit written in Rust
is_public: true
project_name: armyknife
release_type: rust
type: rust
use_release_please: true
